name = "zfit_fort"
version = "0.1.0"
license = "license"
author = "djean032"
maintainer = "djean032@gmail.com"
copyright = "Copyright 2024, djean032"
[dependencies]
stdlib = "*"
minpack = "*"
M_CLI2.git = "https://github.com/urbanjost/M_CLI2"
M_io.git = "https://github.com/urbanjost/M_io"
[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
link = "odepack"
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

